export enum GameMessage {
    PlayerJoined,
	GameStarted,
	YourCards,
	Action,
	ChallengeAction,
	ChallenegeActionResult,
	Block,
	ChallengeBlock,
	ChallengeBlockResult,
	RevealCard,
	ActionResult,
	NextPlayer,
	GameOver,
} 
